#!/usr/bin/env bash
#=================================================
# name:   systray-fzf
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   28/10/2025
#=================================================
output=$(systray-cli | sort)
history=()
header="Applications"
while [[ $output != "" ]]; do
    selection=$(fzf --header="$header" --prompt "> " --with-nth="{2..}" <<< "$output")
    exit_code=$?

    if [[ $exit_code -eq 130 ]]; then # esc pressed
        if [[ ${#history[@]} -ge 2 ]]; then
            unset 'history[-1]'
            selection="${history[-1]}"
            header=" $(cut -f2 <<< "$selection")"
            output=$(systray-cli "$(cut -f1 <<< "$selection")")
            continue
        fi
    fi

    if [[ $selection == "" ]]; then
      exit 0
    fi
    header=" $(cut -f2 <<< "$selection")"
    output=$(systray-cli "$(cut -f1 <<< "$selection")")
    if [[ $output == "" ]]; then
        exit 0
    fi
    history+=("$selection")
done
